INGESTION_QUEUE = "ingestionqueue"
QUERY_QUEUE = "queryqueue"

# *************** Doc Status ****************** #
READ_SUCCESSFULLY = "READ_SUCCESSFULLY"
CHUNKED_SUCCESSFULLY = "CHUNKED_SUCCESSFULLY"
CHUNKING_FAILED = "CHUNKING_FAILED"
EMBEDDED_SUCCESSFULLY = "EMBEDDED_SUCCESSFULLY"
EMBEDDING_FAILED = "EMBEDDING_FAILED"
STORED_SUCCESSFULLY = "STORED_SUCCESSFULLY"
STORAGE_FAILED = "STORAGE_FAILED"

# ************** Asset Status ***************** #
ASSET_INGESTING = "ASSET_INGESTING"
ASSET_INGESTION_SUCCESS = "ASSET_INGESTION_SUCCESS"
ASSET_INGESTION_FAILED = "ASSET_INGESTION_FAILED"
ASSET_DELETING = "ASSET_DELETING"
ASSET_DELETE_FAILED = "ASSET_DELETE_FAILED"
