// THEMES
export const PRIMARY_COLOR = '#0a6dc2'
export const COLOR_BG_BASE = '#141414'

// STATUS COLORS
export const SUCCESS_COLOR = 'rgba(40, 167, 69, 0.5)'
export const ERROR_COLOR = '#B000209F'
export const WARNING_COLOR = '#ffa7009F'
export const INFO_COLOR = '#0a6dc2AF'

// OTHER
export const USER_IMAGES_LOCALSTORAGE_KEY = 'userImages'

// *************** Doc Status ****************** //
export const READ_SUCCESSFULLY = 'READ_SUCCESSFULLY'
export const CHUNKED_SUCCESSFULLY = 'CHUNKED_SUCCESSFULLY'
export const CHUNKING_FAILED = 'CHUNKING_FAILED'
export const EMBEDDED_SUCCESSFULLY = 'EMBEDDED_SUCCESSFULLY'
export const EMBEDDING_FAILED = 'EMBEDDING_FAILED'

// *************** Asset Status ****************** //
export const ASSET_APPROVAL_PENDING = 'ASSET_APPROVAL_PENDING'
export const ASSET_REJECTED = 'ASSET_REJECTED'
export const ASSET_INGESTION_PENDING = 'ASSET_INGESTION_PENDING'
export const ASSET_INGESTING = 'ASSET_INGESTING'
export const ASSET_INGESTION_SUCCESS = 'ASSET_INGESTION_SUCCESS'
export const ASSET_INGESTION_FAILED = 'ASSET_INGESTION_FAILED'
export const ASSET_DELETING = 'ASSET_DELETING'
export const ASSET_DELETE_FAILED = 'ASSET_DELETE_FAILED'
